In [1]:
conda install matplotlib

Note: you may need to restart the kernel to use updated packages.


WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename C:\Users\17374\Anaconda3\pkgs\libclang-9.0.1-default_hf44288c_0.tar.bz2.  Please remove this file manually (you may need to reboot to free file handles)



Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\17374\Anaconda3\envs\pytorch_gpu

  added / updated specs:
    - matplotlib


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cycler-0.10.0              |             py_2           9 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
    icu-64.2                   |       he025d50_1        14.1 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
    kiwisolver-1.1.0           |   py37he980bc4_0          61 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
    libclang-9.0.1             |default_hf44288c_0        20.8 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
    matplotlib-3.2.0           |                1           6 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
    matplotlib-base-3.2.0      |

In [3]:
%matplotlib inline

In [4]:
from __future__ import print_function
import torch

In [5]:
x = torch.empty(5,3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 9.8091e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [6]:
x = torch.rand(5,3)
print(x)

tensor([[0.8332, 0.3659, 0.7665],
        [0.5664, 0.0553, 0.7334],
        [0.1667, 0.0104, 0.3544],
        [0.3377, 0.3070, 0.7128],
        [0.8199, 0.0194, 0.0698]])


In [7]:
x = torch.zeros(5,3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
x = x.new_ones(5,3,dtype = torch.double)
print(x)

x = torch.randn_like(x,dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.7346, -1.7844,  0.0267],
        [ 1.2090, -0.4153, -1.4118],
        [-0.9004, -0.2186,  0.7920],
        [ 1.8555, -1.0867, -0.4301],
        [ 0.5948, -0.2270,  0.6176]])


In [10]:
print(x.size())

torch.Size([5, 3])


In [11]:
y = torch.rand(5,3)

In [12]:
print(x+y)
print(torch.add(x,y))

tensor([[-1.5877, -0.9860,  0.1873],
        [ 1.5040,  0.2424, -0.6988],
        [-0.4606,  0.4649,  0.8110],
        [ 2.0692, -0.7205,  0.1629],
        [ 0.9872, -0.2093,  1.3620]])
tensor([[-1.5877, -0.9860,  0.1873],
        [ 1.5040,  0.2424, -0.6988],
        [-0.4606,  0.4649,  0.8110],
        [ 2.0692, -0.7205,  0.1629],
        [ 0.9872, -0.2093,  1.3620]])


In [13]:
result = torch.empty(5,3)
torch.add(x,y,out = result)
print(result)

tensor([[-1.5877, -0.9860,  0.1873],
        [ 1.5040,  0.2424, -0.6988],
        [-0.4606,  0.4649,  0.8110],
        [ 2.0692, -0.7205,  0.1629],
        [ 0.9872, -0.2093,  1.3620]])


In [14]:
y.add_(x)
print(y)

tensor([[-1.5877, -0.9860,  0.1873],
        [ 1.5040,  0.2424, -0.6988],
        [-0.4606,  0.4649,  0.8110],
        [ 2.0692, -0.7205,  0.1629],
        [ 0.9872, -0.2093,  1.3620]])


In [15]:
print(x[:,1])

tensor([-1.7844, -0.4153, -0.2186, -1.0867, -0.2270])


In [17]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.5727])
-0.5727027058601379


In [19]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [20]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [21]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,b,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [23]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x,device = device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z,z.to("cpu",torch.double))

tensor([0.4273], device='cuda:0')
tensor([0.4273], device='cuda:0') tensor([0.4273], dtype=torch.float64)
